name: goorlanews
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  webview_flutter: ^0.3.20
  url_launcher: ^5.1.4
  url_launcher_web: ^0.1.0
  share: ^0.6.3+6
  test: ^1.14.2
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.6
  cached_network_image: ^2.1.0+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_google_maps: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Bimbi
      fonts:
        - asset: fonts/Bimby.ttf

  assets:
    - images/

